CREATE TABLE CLUB(
        ID_CLUB INT PRIMARY KEY AUTO_INCREMENT,
        TITULO CHAR(100) NOT NULL UNIQUE,
         EDAD_MINIMA TINYINT NOT NULL,
         SEXO_REQUERIDO CHAR(2)  NULL
     );
CREATE TABLE INTEGRANTE(
      ID_INTEGRANTE INT PRIMARY KEY AUTO_INCREMENT,
      NOMBRE CHAR(100),
      EDAD TINYINT NOT NULL,
      SEXO CHAR(2) NOT NULL
);
CREATE TABLE INSCRIPCION(
	  ID_INSCRIPCION INT PRIMARY KEY AUTO_INCREMENT,
	  ID_INTEGRANTE INT NOT NULL,
      CLUB_ID_CLUB INT NOT NULL,
      ROL CHAR(20) NULL,
	  FOREIGN KEY (ID_INTEGRANTE) REFERENCES INTEGRANTE(ID_INTEGRANTE),
      FOREIGN KEY (CLUB_ID_CLUB) REFERENCES CLUB(ID_CLUB)
);

INSERT INTO CLUB values
(1,	'Ajedrez Los Alfiles',	27,	NULL),
(2,	'Futbol Los gallos',	15,	'M'),
(3,	'Basquetbol Francas',	15,	'F'),
(4,	'Voleibol Buenos Aires',	20,	NULL);

INSERT INTO INTEGRANTE VALUES
(10,	'Rene Lopez Gamez',	25,	'M'),
(20,	'Lucas Torres Flores',	13,	'M'),
(30,	'Mirna Arroyo Alcala',	15,	'F'),
(40,	'Talia Ruelas Garcia',	32,	'F');

INSERT INTO INSCRIPCION values
(100,	10,1,	NULL),
(200,	10,2,	'Líder'),
(300,	30,3,	NULL),
(400,	40,3,	'Líder'),
(500,	40,1,	NULL);

