/*
 * Esta aplicacion demuestra la funcionalidad de las transacciones en MySQL.
 */
package Interfaz;

import BaseDatos.Conexion;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class FRMgenealogico extends javax.swing.JFrame {

    Conexion mConexion;

    /**
     * Creates new form FRMcrearCredito
     */
    public FRMgenealogico() {
        mConexion = new Conexion();
        try {
            mConexion.Conectar("192.168.0.100", "genealogico",
                    "user_gen", "admin");
            mConexion.ejecutarActualizacion("set autocommit=0");
        } catch (Exception error) {
            System.out.println(error.toString());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNnuevo = new javax.swing.JButton();
        BTNconsultar = new javax.swing.JButton();
        BTNdeshacerUltimo = new javax.swing.JButton();
        BTNconfirmar = new javax.swing.JButton();
        BTNdeshacerTodo = new javax.swing.JButton();
        TXTidpredecesor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLpersonas = new javax.swing.JTable();
        TXTnombre_predecesor = new javax.swing.JTextField();
        BTNiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNnuevo.setText("Agregar persona");
        BTNnuevo.setEnabled(false);
        BTNnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNnuevoActionPerformed(evt);
            }
        });

        BTNconsultar.setText("Consultar personas");
        BTNconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNconsultarActionPerformed(evt);
            }
        });

        BTNdeshacerUltimo.setText("Deshacer ultimo");
        BTNdeshacerUltimo.setEnabled(false);
        BTNdeshacerUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdeshacerUltimoActionPerformed(evt);
            }
        });

        BTNconfirmar.setText("Confirmar todo");
        BTNconfirmar.setEnabled(false);
        BTNconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNconfirmarActionPerformed(evt);
            }
        });

        BTNdeshacerTodo.setText("Deshacer todo");
        BTNdeshacerTodo.setEnabled(false);
        BTNdeshacerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdeshacerTodoActionPerformed(evt);
            }
        });

        TXTidpredecesor.setEditable(false);
        TXTidpredecesor.setToolTipText("Selecciona una persona de la tabla de la derecha");

        jLabel2.setText("Predecesor:");

        jLabel3.setText("Nombre:");

        TBLpersonas.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TBLpersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBLpersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLpersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLpersonas);

        TXTnombre_predecesor.setEditable(false);
        TXTnombre_predecesor.setToolTipText("Selecciona una persona de la tabla de la derecha");

        BTNiniciar.setText("Iniciar transaccion");
        BTNiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTidpredecesor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTnombre_predecesor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BTNnuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNiniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNdeshacerUltimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNdeshacerTodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNconsultar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXTidpredecesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTnombre_predecesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNiniciar)
                            .addComponent(BTNconsultar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNnuevo)
                            .addComponent(BTNdeshacerUltimo))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNconfirmar)
                            .addComponent(BTNdeshacerTodo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNnuevoActionPerformed
        try {
            //Poner un savepoint
            String sql = "savepoint ultimo";
            mConexion.ejecutarActualizacion(sql);

            //Insertamos el registro de PRESTAMO
            if (TXTidpredecesor.getText().equals("")) {
                sql = "insert into persona values(null,'?2',null)";
            } else {
                sql = "insert into persona values(null,'?2','?3')";
            }
            sql = sql.replace("?2", TXTnombre.getText());
            sql = sql.replace("?3", TXTidpredecesor.getText());
            mConexion.ejecutarActualizacion(sql);
        } catch (Exception error) {
            System.out.println(error.toString());
        }
    }//GEN-LAST:event_BTNnuevoActionPerformed

    private void BTNconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNconsultarActionPerformed
        try {
            //Consultamos la tabla de personas
            String sql = "select A.idpersona,A.nombre,B.nombre as predecesor from persona A left join persona B "
                    + " on A.idpredecesor=B.idpersona";
            ResultSet listaPersonas = mConexion.ejecutarConsulta(sql);
            if (listaPersonas != null) {
                Object[] encabezado = {"idPersona", "Nombre", "Predecesor"};
                DefaultTableModel modelo
                        = new DefaultTableModel(null, encabezado);
                while (listaPersonas.next()) {
                    Object[] fila = {
                        listaPersonas.getString("idPersona"),
                        listaPersonas.getString("nombre"),
                        listaPersonas.getString("predecesor")
                    };
                    modelo.addRow(fila);
                }
                TBLpersonas.setModel(modelo);
            }//
        } catch (Exception error) {
            System.out.println(error.toString());
        }
    }//GEN-LAST:event_BTNconsultarActionPerformed

    private void BTNconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNconfirmarActionPerformed
        try {
            mConexion.ejecutarActualizacion("commit");
            inicializarBotones(false);
        } catch (Exception error) {
            System.out.println(error.toString());
        }
    }//GEN-LAST:event_BTNconfirmarActionPerformed

    private void BTNdeshacerUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdeshacerUltimoActionPerformed
        try {
            mConexion.ejecutarActualizacion(
                    "rollback to savepoint ultimo");
        } catch (Exception error) {
            System.out.println(error.toString());
        }
    }//GEN-LAST:event_BTNdeshacerUltimoActionPerformed

    private void BTNdeshacerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdeshacerTodoActionPerformed
        try {
            mConexion.ejecutarActualizacion(
                    "rollback");
            inicializarBotones(false);
        } catch (Exception error) {
            System.out.println(error.toString());
        }
    }//GEN-LAST:event_BTNdeshacerTodoActionPerformed

    private void BTNiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNiniciarActionPerformed
        //Iniciamos una transaccion
        try {
            mConexion.ejecutarActualizacion(
                    "start transaction");
            inicializarBotones(true);
        } catch (Exception error) {
            System.out.println(error.toString());
        }
    }//GEN-LAST:event_BTNiniciarActionPerformed

    private void TBLpersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLpersonasMouseClicked
        int fila = TBLpersonas.getSelectedRow();
        if (fila >= 0) {
            int id = Integer.parseInt(TBLpersonas.getValueAt(fila, 0).toString());
            TXTidpredecesor.setText(String.valueOf(id));
            String nombre = TBLpersonas.getValueAt(fila, 1).toString();
            TXTnombre_predecesor.setText(nombre);
        }
    }//GEN-LAST:event_TBLpersonasMouseClicked

    private void inicializarBotones(boolean estado) {
        //Habilitar los demas botones
        BTNnuevo.setEnabled(estado);
        BTNconfirmar.setEnabled(estado);
        BTNdeshacerTodo.setEnabled(estado);
        BTNdeshacerUltimo.setEnabled(estado);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMgenealogico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMgenealogico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMgenealogico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMgenealogico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMgenealogico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNconfirmar;
    private javax.swing.JButton BTNconsultar;
    private javax.swing.JButton BTNdeshacerTodo;
    private javax.swing.JButton BTNdeshacerUltimo;
    private javax.swing.JButton BTNiniciar;
    private javax.swing.JButton BTNnuevo;
    private javax.swing.JTable TBLpersonas;
    private javax.swing.JTextField TXTidpredecesor;
    private javax.swing.JTextField TXTnombre;
    private javax.swing.JTextField TXTnombre_predecesor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
